name: autocomplete_textfield
description: A simple and versatile autocomplete text field for flutter, supporting multiple datatypes, now featuring listsview .
version: 1.7.5
author: Felix McCuaig <felixmccuaigdev@gmail.com> || José Eduardo Teixeira <joseeduardot@developmentparadise.com>
homepage: https://github.com/felixlucien/flutter-autocomplete-textfield

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter